/*
 * generated by Xtext
 */
package gama.gaml.compiler.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGamlScopeProvider extends DelegatingScopeProvider {
}
