/**
 * generated by Xtext
 */
package gama.gaml.compiler.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Double Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gama.gaml.compiler.gaml.GamlPackage#getDoubleLiteral()
 * @model
 * @generated
 */
public interface DoubleLiteral extends TerminalExpression
{
} // DoubleLiteral
