/**
 * generated by Xtext
 */
package gama.gaml.compiler.gaml;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entry</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gama.gaml.compiler.gaml.GamlPackage#getEntry()
 * @model
 * @generated
 */
public interface Entry extends EObject
{
} // Entry
