/**
 * generated by Xtext
 */
package gama.gaml.compiler.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SSet</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gama.gaml.compiler.gaml.GamlPackage#getS_Set()
 * @model
 * @generated
 */
public interface S_Set extends S_Assignment
{
} // S_Set
