/**
 * generated by Xtext
 */
package gama.gaml.compiler.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>species Or Grid Display Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gama.gaml.compiler.gaml.GamlPackage#getspeciesOrGridDisplayStatement()
 * @model
 * @generated
 */
public interface speciesOrGridDisplayStatement extends Statement
{
} // speciesOrGridDisplayStatement
