/**
 * generated by Xtext
 */
package gama.gaml.compiler.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gama.gaml.compiler.gaml.GamlPackage#getVarDefinition()
 * @model
 * @generated
 */
public interface VarDefinition extends GamlDefinition
{
} // VarDefinition
