/**
 * generated by Xtext
 */
package gama.gaml.compiler.gaml.impl;

import org.eclipse.emf.ecore.EClass;

import gama.gaml.compiler.gaml.EquationDefinition;
import gama.gaml.compiler.gaml.GamlPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Equation Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EquationDefinitionImpl extends GamlDefinitionImpl implements EquationDefinition
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EquationDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamlPackage.Literals.EQUATION_DEFINITION;
  }

} //EquationDefinitionImpl
