/**
 * generated by Xtext
 */
package gama.gaml.compiler.gaml.impl;

import org.eclipse.emf.ecore.EClass;

import gama.gaml.compiler.gaml.GamlPackage;
import gama.gaml.compiler.gaml.S_DirectAssignment;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>SDirect Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class S_DirectAssignmentImpl extends S_AssignmentImpl implements S_DirectAssignment
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected S_DirectAssignmentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamlPackage.Literals.SDIRECT_ASSIGNMENT;
  }

} //S_DirectAssignmentImpl
