# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Compilation Test

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  workflow_dispatch:  # For manual trigger

jobs:
  # 
  # GENERIC BUILD
  # 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Adopt OpenJDK 17
        uses: actions/setup-java@v2 
        with:
          distribution: 'temurin'
          java-version: '17'
          java-package: jdk

      - name: Compilation
        working-directory: ${{ github.workspace }}/gama.gaml.parent/
        run: mvn clean install

